name       : kunitconversion
version    : 5.85.0
release    : 52
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.85/kunitconversion-5.85.0.tar.xz : 1e0af3093cf376790a22ef80bf3df094c57ffcd9427da6ba73089e6a71ab9665
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.0-or-later
component  : programming.library
summary    : Converting physical units
description: |
    KUnitConversion provides functions to convert values in different physical units. It supports converting different prefixes (e.g. kilo, mega, giga) as well as converting between different unit systems (e.g. liters, gallons).
optimize   : lto
builddeps  :
    - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
