name       : kunitconversion
version    : 5.35.0
release    : 3
source     :
    - https://download.kde.org/stable/frameworks/5.35/kunitconversion-5.35.0.tar.xz : 2acf7012e14177bb444a802686459b628f9564c26a30fbc632104fa6a91c0dcc
license    : LGPL-2.1
component  : programming
summary    : Converting physical units
description: |
    KUnitConversion provides functions to convert values in different physical units. It supports converting different prefixes (e.g. kilo, mega, giga) as well as converting between different unit systems (e.g. liters, gallons).
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - ki18n-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
