name       : kunitconversion
version    : 5.44.0
release    : 11
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.44/kunitconversion-5.44.0.tar.xz : b4758c0ab13eec9b19247db06ee00f6c4e2228a838044cc78337655f79a827ff
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Converting physical units
description: |
    KUnitConversion provides functions to convert values in different physical units. It supports converting different prefixes (e.g. kilo, mega, giga) as well as converting between different unit systems (e.g. liters, gallons).
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - ki18n-devel
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
