name       : kunitconversion
version    : 5.96.0
release    : 61
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.96/kunitconversion-5.96.0.tar.xz : 6f9ceaf755fbfb61d427f5a4ee2ed06042b6a0c4991380d5b7c1f297c2189ae2
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.0-or-later
component  : programming.library
summary    : Converting physical units
description: |
    KUnitConversion provides functions to convert values in different physical units. It supports converting different prefixes (e.g. kilo, mega, giga) as well as converting between different unit systems (e.g. liters, gallons).
optimize   : lto
builddeps  :
    - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
