name       : kunitconversion
version    : 5.63.0
release    : 30
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.63/kunitconversion-5.63.0.tar.xz : ffe759050f0ac56d26049906b7beb5be8bc16d15917a16d287962725bb14f87b
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Converting physical units
description: |
    KUnitConversion provides functions to convert values in different physical units. It supports converting different prefixes (e.g. kilo, mega, giga) as well as converting between different unit systems (e.g. liters, gallons).
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
