name       : kunitconversion
version    : 5.69.0
release    : 36
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.69/kunitconversion-5.69.0.tar.xz : f0ae5d328063e0ea5e93ad61c7d925bb17a3b761040dafe76eea4a468be15fff
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.library
optimize   : lto
summary    : Converting physical units
description: |
    KUnitConversion provides functions to convert values in different physical units. It supports converting different prefixes (e.g. kilo, mega, giga) as well as converting between different unit systems (e.g. liters, gallons).
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
