name       : kunitconversion
version    : 5.93.0
release    : 59
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.93/kunitconversion-5.93.0.tar.xz : 9baefb6aed92d2b32727f9492f1322a9e0b17b609c2d82296f4ee10b55a02fc8
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.0-or-later
component  : programming.library
summary    : Converting physical units
description: |
    KUnitConversion provides functions to convert values in different physical units. It supports converting different prefixes (e.g. kilo, mega, giga) as well as converting between different unit systems (e.g. liters, gallons).
optimize   : lto
builddeps  :
    - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
