name       : kunitconversion
version    : 5.72.0
release    : 39
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.72/kunitconversion-5.72.0.tar.xz : 419d415191cfecba074b2160b292c670de17ba1dd88ab031f8ced56dc6cbb827
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.library
optimize   : lto
summary    : Converting physical units
description: |
    KUnitConversion provides functions to convert values in different physical units. It supports converting different prefixes (e.g. kilo, mega, giga) as well as converting between different unit systems (e.g. liters, gallons).
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
