name       : kunitconversion
version    : 5.51.0
release    : 18
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.51/kunitconversion-5.51.0.tar.xz : 8605975eb05031e3e2d0295ca577c3010c45b00cd9daec2cf9c1861998bd9629
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Converting physical units
description: |
    KUnitConversion provides functions to convert values in different physical units. It supports converting different prefixes (e.g. kilo, mega, giga) as well as converting between different unit systems (e.g. liters, gallons).
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
