name       : kunitconversion
version    : 5.83.0
release    : 50
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.83/kunitconversion-5.83.0.tar.xz : 6e82f0024256c9da5a4892e96f28c19377e4859dceb78333de6ad0a2c6617105
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.0-or-later
component  : programming.library
summary    : Converting physical units
description: |
    KUnitConversion provides functions to convert values in different physical units. It supports converting different prefixes (e.g. kilo, mega, giga) as well as converting between different unit systems (e.g. liters, gallons).
optimize   : lto
builddeps  :
    - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
