name       : kunitconversion
version    : 5.80.0
release    : 47
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.80/kunitconversion-5.80.0.tar.xz : 94ac5214e4a990ae569f2e4bdc66d2d6f46b60a225ee9f90274c4b39e69093c1
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.0-or-later
component  : programming.library
summary    : Converting physical units
description: |
    KUnitConversion provides functions to convert values in different physical units. It supports converting different prefixes (e.g. kilo, mega, giga) as well as converting between different unit systems (e.g. liters, gallons).
optimize   : lto
builddeps  :
    - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
